### ISSUE TITLE
Necessário atualizar o url_base

### ISSUE THREAD

**Issue by wesleydionisio** [gabsdocompiuter/jornal-do-povo-pdf#4]
Funcionou perfeitamente até dia 11/08, porém agora é necessário remover o sufixo `_copy` da url.

            url = f'{self.url_base}/cliente/img/edicao/{date}/jpg/{day}pg{str(counter).zfill(2)}.jpg'

**Comment by gabsdocompiuter** [comment]
Opa!

Obrigado, vou ajudar.
Estou pensando em alguma forma de deixar essa URL mais dinâmica, talvez com algum arquivo de configuração
